
package be.kzen.ergorr.interfaces.soap.rim;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ebXMLRegistrySOAPService", targetNamespace = "http://www.kzen.be/ergorr/interfaces/soap/rim", wsdlLocation = "WEB-INF/wsdl/RIM-service.wsdl")
public class EbXMLRegistrySOAPService
    extends Service
{

    private final static URL EBXMLREGISTRYSOAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(be.kzen.ergorr.interfaces.soap.rim.EbXMLRegistrySOAPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = be.kzen.ergorr.interfaces.soap.rim.EbXMLRegistrySOAPService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/yamanustuntas/workspace/projects/ESA/trunk/source/ErgoRR/web/WEB-INF/wsdl/RIM-service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/yamanustuntas/workspace/projects/ESA/trunk/source/ErgoRR/web/WEB-INF/wsdl/RIM-service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EBXMLREGISTRYSOAPSERVICE_WSDL_LOCATION = url;
    }

    public EbXMLRegistrySOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EbXMLRegistrySOAPService() {
        super(EBXMLREGISTRYSOAPSERVICE_WSDL_LOCATION, new QName("http://www.kzen.be/ergorr/interfaces/soap/rim", "ebXMLRegistrySOAPService"));
    }

    /**
     * 
     * @return
     *     returns QueryManagerPortType
     */
    @WebEndpoint(name = "QueryManagerPort")
    public QueryManagerPortType getQueryManagerPort() {
        return super.getPort(new QName("http://www.kzen.be/ergorr/interfaces/soap/rim", "QueryManagerPort"), QueryManagerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryManagerPortType
     */
    @WebEndpoint(name = "QueryManagerPort")
    public QueryManagerPortType getQueryManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.kzen.be/ergorr/interfaces/soap/rim", "QueryManagerPort"), QueryManagerPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns LifeCycleManagerPortType
     */
    @WebEndpoint(name = "LifeCycleManagerPort")
    public LifeCycleManagerPortType getLifeCycleManagerPort() {
        return super.getPort(new QName("http://www.kzen.be/ergorr/interfaces/soap/rim", "LifeCycleManagerPort"), LifeCycleManagerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LifeCycleManagerPortType
     */
    @WebEndpoint(name = "LifeCycleManagerPort")
    public LifeCycleManagerPortType getLifeCycleManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.kzen.be/ergorr/interfaces/soap/rim", "LifeCycleManagerPort"), LifeCycleManagerPortType.class, features);
    }

}
