
package be.kzen.ergorr.interfaces.soap.rim;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import be.kzen.ergorr.model.query.AdhocQueryRequest;
import be.kzen.ergorr.model.query.AdhocQueryResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryManagerPortType", targetNamespace = "http://www.kzen.be/ergorr/interfaces/soap/rim")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    be.kzen.ergorr.model.eo.opt.ObjectFactory.class,
    be.kzen.ergorr.model.wrs.ObjectFactory.class,
    be.kzen.ergorr.model.eo.sar.ObjectFactory.class,
    be.kzen.ergorr.model.ows.ObjectFactory.class,
    be.kzen.ergorr.model.eo.atm.ObjectFactory.class,
    be.kzen.ergorr.model.rim.ObjectFactory.class,
    be.kzen.ergorr.model.csw.ObjectFactory.class,
    be.kzen.ergorr.model.eo.eop.ObjectFactory.class,
    be.kzen.ergorr.model.rs.ObjectFactory.class,
    be.kzen.ergorr.model.lcm.ObjectFactory.class,
    be.kzen.ergorr.model.query.ObjectFactory.class,
    be.kzen.ergorr.model.purl.elements.ObjectFactory.class,
    be.kzen.ergorr.model.purl.terms.ObjectFactory.class,
    be.kzen.ergorr.model.gml.ObjectFactory.class,
    be.kzen.ergorr.model.ogc.ObjectFactory.class
})
public interface QueryManagerPortType {


    /**
     * 
     * @param partAdhocQueryRequest
     * @return
     *     returns be.kzen.ergorr.model.query.AdhocQueryResponse
     */
    @WebMethod(action = "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:bindings:3.0:QueryManagerPortType#submitAdhocQuery")
    @WebResult(name = "AdhocQueryResponse", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", partName = "partAdhocQueryResponse")
    public AdhocQueryResponse submitAdhocQuery(
        @WebParam(name = "AdhocQueryRequest", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", partName = "partAdhocQueryRequest")
        AdhocQueryRequest partAdhocQueryRequest);

}
